/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.12.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

rootProject.name = "jvm-monorepo"

fun allProjectsUnder(dir: File): Array<String> {

  val listFiles = dir.walkTopDown().map { it }
  return if (listFiles.none()) arrayOf()
  else {
    listFiles
      .filter { it.isFile && it.name.equals("build.gradle.kts", ignoreCase = true) }
      .map { it.parentFile.toRelativeString(rootDir).replace("/", ":") }
      .toList()
      .toTypedArray()
  }
}

include(
  listOf(
    *(allProjectsUnder(rootDir.resolve("packages/apps"))),
    *(allProjectsUnder(rootDir.resolve("packages/libraries"))),
  )
)
