#!/bin/bash
echo "*************************************************"
echo "running git pre-commit hook..."
echo "*************************************************"

stagedFiles=$(git diff --staged --name-only)

./gradlew spotlessApply

status=$?

if [ "$status" = 0 ]; then
  for file in $stagedFiles; do
    if test -f "$file"; then
      git add "$file"
    fi
  done
  echo "*************************************************"
  echo "pre-commit hook executed successfully..."
  echo "*************************************************"
  exit 0
else
  echo "*************************************************"
  echo "pre-commit hook failed..."
  echo 1>&2 "spotlessApply found violations it could not fix."
  echo "Run ./gradlew spotlessApply in your terminal and fix the issues before trying to commit."
  echo "*************************************************"
  exit 1
fi